version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: go run cmd/core/main.go
    restart: always
    container_name: api
